[package]
name = "fractal-trick"
version = "0.1.0"
authors = ["Daniil Rose <daniil.rose@posteo.org>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "0.3.4"
lazy_static = "1.4.0"
colorsys = "0.6.7"
